services:
  aws-cli:
    image: amazon/aws-cli:latest
    container_name: aws-cli
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_DEFAULT_REGION=${S3_REGION}
    volumes:
      - aws_config:/root/.aws
      - ../../../../websites:/websites
      - ../../config/aws:/scripts
    networks:
      - webserver-network
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # Install necessary packages
      yum update -y && yum install -y bash curl tar gzip wget

      # Create AWS config directory
      mkdir -p /root/.aws

      # Create AWS credentials file
      cat > /root/.aws/credentials << EOF
      [default]
      aws_access_key_id = $${AWS_ACCESS_KEY_ID}
      aws_secret_access_key = $${AWS_SECRET_ACCESS_KEY}
      EOF

      # Create AWS config file
      cat > /root/.aws/config << EOF
      [default]
      region = $${AWS_DEFAULT_REGION}
      output = json
      EOF

      # Set proper permissions
      chmod 600 /root/.aws/credentials
      chmod 600 /root/.aws/config

      echo 'AWS CLI configured successfully!'
      echo 'AWS CLI version:' \$(aws --version)
      echo 'Available websites to backup:'
      ls -la /websites/

      # Test AWS connectivity
      echo 'Testing AWS S3 connectivity...'
      aws --endpoint-url http://seaweedfs-s3:8333 s3 ls || echo 'Note: S3 test failed - check your credentials and region'

      # Keep container running
      tail -f /dev/null
      "

networks:
  webserver-network:
    external: true

volumes:
  aws_config:
