services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    command: ["--smtp-auth-allow-insecure"]
    environment:
      - MP_SMTP_AUTH=${MAILPIT_USERNAME}:${MAILPIT_PASSWORD}
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"   # SMTP
      - "${MAILPIT_UI_PORT:-8025}:8025"     # Web UI
    networks:
      - webserver-network

networks:
  webserver-network:
    external: true
