services:
  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    container_name: seaweedfs-master
    command: "master -ip=seaweedfs-master -mdir=/data -volumePreallocate=false -volumeSizeLimitMB=1024"
    volumes:
      - ./data/seaweedfs/master:/data
    networks:
      - webserver-network

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    container_name: seaweedfs-volume
    command: "volume -mserver=seaweedfs-master:9333 -ip=seaweedfs-volume -dir=/data -max=50"
    depends_on:
      - seaweedfs-master
    volumes:
      - ./data/seaweedfs/volume:/data
    networks:
      - webserver-network

  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    container_name: seaweedfs-filer
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "apk add --no-cache postgresql-client && sh /scripts/check_create_filemeta.sh && weed filer -master=seaweedfs-master:9333 -ip=seaweedfs-filer -port=8888 -defaultReplicaPlacement=000 -disableDirListing=true -exposeDirectoryData=false"
    depends_on:
      - seaweedfs-master
    environment:
      - SEAWEED_POSTGRES_HOST=${SEAWEED_POSTGRES_HOST}
      - SEAWEED_POSTGRES_PORT=${SEAWEED_POSTGRES_PORT}
      - SEAWEED_POSTGRES_USER=${SEAWEED_POSTGRES_USER}
      - SEAWEED_POSTGRES_PASSWORD=${SEAWEED_POSTGRES_PASSWORD}
      - SEAWEED_POSTGRES_DB=${SEAWEED_POSTGRES_DB}
    networks:
      - webserver-network
    volumes:
      - ./data/seaweedfs/filer:/data
      - ../../config/seaweedfs/check_create_filemeta.sh:/scripts/check_create_filemeta.sh

  seaweedfs-s3:
    image: chrislusf/seaweedfs:latest
    restart: unless-stopped
    container_name: seaweedfs-s3
    command: "s3 -filer=seaweedfs-filer:8888 -ip.bind=0.0.0.0 -port=8333 -config=/config/s3.json"
    depends_on:
      - seaweedfs-filer
    networks:
      - webserver-network
    volumes:
      - ../../config/seaweedfs/s3.json:/config/s3.json:ro

networks:
  webserver-network:
    external: true
