services:
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "28888:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      # Optionally, set PMA_ARBITRARY=1 to allow connecting to any server
    networks:
      - webserver-network

networks:
  webserver-network:
    external: true