services:
  redis:
    container_name: redis
    image: redis:8.0.1
    restart: unless-stopped
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}",
      "--appendonly", "yes",
      "--appendfsync", "everysec",
      "--save", "900", "1",
      "--save", "300", "10", 
      "--save", "60", "10000"
    ]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    networks:
      - webserver-network

networks:
  webserver-network:
    external: true
  database-internal:
    driver: bridge
    internal: true